[build]
  command = "./build.sh"
  publish = "packages/store/dist"
  functions = "packages/store/dist/functions/product"
# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
